# Numpy

<h2 style="color:skyblue;">Introduction</h2> 

* NumPy is a Python library used for working with arrays​ 
    
 * NumPy was created in 2005 by Travis Oliphant.​ 
    
* It is open source​ 
    
* The array object in NumPy is called ndarray

* NumPy stands for Numerical Python

<h3 style="color:skyblue;">Why use numpy?</h3>

* has array object which is 50x faster than Python list
  
* functions for working in domain of linear algebra, fourier transform, and matrices​
  
* the array object in NumPy is called ndarray

<h3 style="color:skyblue;"> Why numpy is faster? </h3>

 * NumPy arrays are stored at one continuous place in memory unlike lists (locality of reference)
   
 * written in C or C++ for fast computation (python is partially used)

# Import Numpy

In [2]:
import numpy as np
import random

# Create numpy arrays

In [11]:
zeros_array = np.zeros((2, 3))  # 2x3 array of zeros
ones_array = np.ones((3, 3))    # 3x3 array of ones
random_array = np.random.rand(4, 5)  # 2x2 array of random numbers

In [12]:
print(random_array)

[[0.75688751 0.50030761 0.57147741 0.5974266  0.7587832 ]
 [0.14062962 0.4639948  0.81684894 0.60873776 0.03603902]
 [0.29719385 0.3268313  0.14824401 0.83442925 0.15958825]
 [0.13534633 0.65951921 0.47953409 0.42801135 0.65664626]]


# Accessing and Slicing

In [13]:
random_array[0][0]

0.7568875102883442

In [14]:
random_array[-1][-1]

0.6566462566526303

In [17]:
random_array[0:2][-1][0:2]

array([0.14062962, 0.4639948 ])

# Airthmetic

In [18]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Aggregation functions

In [20]:
print(np.sum(random_array))
print(np.mean(random_array))
print(np.median(random_array))
print(np.min(random_array))
print(np.max(random_array))

9.376476374087945
0.46882381870439727
0.4899208470493422
0.036039024880918036
0.8344292495839442


# Reshaping

In [26]:
reshaped_array = random_array.reshape(5, 4)  # Reshape to a 5x4 array

# Transposing

In [28]:
transposed_array = reshaped_array.T

# Broadcasting

In [30]:
scalar = 2
result = reshaped_array + scalar

# list to arrays

In [34]:
list1 = [[1,2,3,4,5],
         [3,4,5,6,7]]
np.array(list1)

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [35]:
list(np.array(list1))

[array([1, 2, 3, 4, 5]), array([3, 4, 5, 6, 7])]